name: PHP Base Template

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
      coverage:
        required: false
        type: string
        default: 'none'
      command:
        required: false
        type: string
        default: 'echo "No command"'
      artifact-path:
        required: false
        type: string
        default: ''
      php-version-artifact:
        required: false
        type: string
        default: ''

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          coverage: ${{ inputs.coverage }}
          tools: composer

      - uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

      - run: composer install --no-progress --prefer-dist

      - name: Run custom command
        run: ${{ inputs.command }}

      - name: Upload artifacts
        if: ${{ (inputs.artifact-path != '') && (inputs.php-version == inputs.php-version-artifact) }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ inputs.php-version-artifact }}
          path: ${{ inputs.artifact-path }}