name: Static analysis

on:
  push:
    branches: [main, dev]
    paths-ignore: ["**.md", "docs/**"]
  pull_request:
    paths-ignore: ["**.md", "docs/**"]

jobs:
  coding-standards:
    strategy:
      matrix:
        php: ["8.3", "8.4"]
    uses: ./.github/workflows/php-base.yml
    with:
      php-version: ${{ matrix.php }}
      command: composer check:static
