name: Unit tests

on:
  push:
    branches: [main, dev]
    paths-ignore: ["**.md", "docs/**"]
  pull_request:
    paths-ignore: ["**.md", "docs/**"]

jobs:
  unit-tests:
    strategy:
      matrix:
        php: ["8.1", "8.2", "8.3"]
    uses: ./.github/workflows/php-base.yml
    with:
      php-version: ${{ matrix.php }}
      command: composer tests
      coverage: 'xdebug'
      artifact-path: 'coverage-unit.xml'
      php-version-artifact: '8.1'

  coverage:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage-8.1

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage-unit.xml
